apiVersion: v1
kind: ConfigMap
metadata:
  name: lung-cancer-config
  labels:
    app: explainable-lung-cancer
data:
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
  MAX_UPLOAD_SIZE_MB: "10"
  FASTAPI_URL: "http://fastapi-service:8000"
